### ISSUE TITLE
Error with latest kace version

### ISSUE THREAD

**Issue by johnbodden** [frenchsomething/kace-ftp-backup#3]
Thanks for this script, it has been working great, but I installed the latest patch and this script stopped working with the following error. This is version  v.6.4.120756

You cannot call a method on a null-valued expression.
At G:\dbbackups\kacebackupsnew.ps1:256 char:43
-         $readlength = $responsestream.Read <<<< ($readbuffer,0,1024)
  - CategoryInfo          : InvalidOperation: (Read:String) [], RuntimeExcep
    tion
  - FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by frenchsomething** [comment]
Hi John,

Thanks for reporting this. I just pushed an update to the master. This wasn't an incompatibility with the SP2 update, but rather I believe the update caused your server to skip a backup. These updates should more gracefully handle times when a backup for that day isn't present on the server. These were my change notes for this update:

-Added a check at top of main that checks for connectivity to FTP server and fails gracefully/emails error report if server is inaccessible.
-Added checks for presence of Incremental & Base files to also fail gracefully/email error report. Previously, I had been assuming that if the backup process was no longer running, that the proper files would therefore be present.

Thanks!
Jared

**Comment by johnbodden** [comment]
You're welcome, thanks for the quick fix. It's a very useful tool

Sent from Outlook Mobile

On Fri, Mar 18, 2016 at 2:27 PM -0700, "frenchsomething" notifications@github.com wrote:

Hi John,

Thanks for reporting this. I just pushed an update to the master. This wasn't an incompatibility with the SP2 update, but rather I believe the update caused your server to skip a backup. These updates should more gracefully handle times when a backup for that day isn't present on the server. These were my change notes for this update:

-Added a check at top of main that checks for connectivity to FTP server and fails gracefully/emails error report if server is inaccessible.

-Added checks for presence of Incremental & Base files to also fail gracefully/email error report. Previously, I had been assuming that if the backup process was no longer running, that the proper files would therefore be present.

Thanks!

Jared
